stages:
  - build
  - test
  - deploy

test_backend:
  stage: test
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd Auction_backend/
  script:
    - mvn test
  tags:
    - ugrad


build_backend:
  stage: build
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd Auction_backend/
  script:
    - mvn clean install
  tags:
    - ugrad