stages:
  - build
  - test
  - publish
  - deploy

variables:
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD:  ""

build_frontend:
  stage: build
  image: node:latest
  before_script:
    - cd Auction_frontend/
  script:
    - echo "build frontEnd"
    - npm install
    - npm install -g @angular/cli
    - ng build
  tags:
    - dalfcs_docker_kvm
    
build_backend:
  stage: build
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd Auction_backend/
  script:
    - echo "Build backend"
    - mvn clean install -DskipTests
  tags:
    - dalfcs_docker_kvm

test_backend:
  stage: test
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd Auction_backend/
  script:
    - echo "Running Tests"
    - mvn test
  tags:
    - dalfcs_docker_kvm

publish_frontend:
  stage: publish
  image: docker:latest
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - cd Auction_frontend/
  script:
    - echo $DOCKER_HOST
    - docker --version
    - echo "Logging Docker"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
    - echo "Building the Docker image"
    - docker build -t docker.io/bidwise/auctionfrontend .
    - echo "Successfully build the docker image"
    - docker push docker.io/bidwise/auctionfrontend
  after_script:
    - echo "Docker Image pushed successfully"
    - docker logout
  when: manual
  tags:
    - dalfcs_docker_kvm