stages:
  - build
  - test
  - deploy

test_backend:
  stage: test
  image: mvn:latest
  before_script:
    - cd Auction_backend/
  script:
    - mvn test
  tags:
    - dalfcs_docker_kvm


build_backend:
  stage: build
  image: mvn:latest
  before_script:
    - cd Auction_backend/
  script:
    - mvn clean install
  tags:
    - dalfcs_docker_kvm